### ISSUE TITLE
How to remove package-info.java if add a plugin jaxb-xew-plugin to maven-jaxb2-plugin

### ISSUE THREAD

**Issue by ghost** [highsource/jaxb2-annotate-plugin#15] opened 2015-09-10 13:18 UTC
I ask the question before, but get an comments that use annotate-plugin. Do you mean annox:annotate?
Can maven-jaxb2-plugin support @XmlRootElement and @XmlWrappper directly?

**Comment by highsource** [comment] 2015-09-10 19:38
> I ask the question before, but get an comments that use annotate-plugin. Do you mean annox:annotate?

I mean this very plugin, `jaxb2-annotate-plugin`.

> Can maven-jaxb2-plugin support @XmlRootElement and @XmlWrappper directly?

No. `maven-jaxb2-plugin` "just" invokes XJC in the frame of a Maven build. You may use JAXB plugins (like `jaxb2-annotate-plugin` or `jaxb-xew-plugin`) if you need additional functionality.

You write that `package-info.java` is added. Why is it an issue for you?
I'm not sure why is it added and which of the two plugins you're supposedly use causes this. Please send me a PR of a test project under https://github.com/highsource/jaxb2-annotate-plugin-support/x/xew which reproduces this behaviour.

**Comment by highsource** [comment] 2018-05-24 20:05
@ghost  I'm closing this due to no reaction.

**Closed by highsource** 2018-05-24 20:05 UTC
Labels: question
